In [5]:
import pandas as pd

#파일경로를 찾고 변수 file_path에 저장
file_path= 'C:/data/4part/bicycle.csv'

#read csv()함수로 데이터프레임 변환
df1= pd.read_csv(file_path, engine='python', encoding='CP949')
df1

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,NaN
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,NaN,10.0,1380.0
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0
...,...,...,...,...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.0,11.0,2200.0
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,14.0,2019-11-15 9:37,101,(구)합정동 주민센터,NaN,5.0,NaN
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53,101,(구)합정동 주민센터,1.0,12.0,2280.0
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0

In [12]:
import pandas as pd

file_path='C:/data/4part/bicycle.xlsx'

df2= pd.read_excel(file_path)
df2

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 08:48:31,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 09:01:24,3,중랑센터,7.0,12.0,1100.0
1,SPB-16216,2019-11-04 08:38:39,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 08:56:33,3,중랑센터,2.0,7.0,1420.0
2,SPB-21097,2019-11-04 08:46:37,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 08:57:35,3,중랑센터,7.0,10.0,NaN
3,SPB-22292,2019-11-05 08:34:59,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 08:45:45,3,중랑센터,NaN,10.0,1380.0
4,SPB-07935,2019-11-05 12:29:00,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39:37,3,중랑센터,7.0,10.0,1650.0
...,...,...,...,...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 04:22:13,112,극동방송국 앞,5.0,2019-11-15 04:33:40,101,(구)합정동 주민센터,1.0,11.0,2200.0
416,SPB-17768,2019-11-15 09:31:48,103,망원역 2번출구 앞,14.0,2019-11-15 09:37:56,101,(구)합정동 주민센터,NaN,5.0,NaN
417,SPB-18841,2019-11-15 20:40:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53:46,101,(구)합정동 주민센터,1.0,12.0,2280.0
418,SPB-24467,2019-11-15 21:55:13,152,마포구민체육센터 앞,18.0,2019-11-15 22:05:40,101,(구)합정동 주민센터,1.0,10.0,1180.0
419,SPB-17570,2019-11-15 22:16:08,391,정동길입구,7.0,2019-11-15 23:04:53,101,(구)합정동 주민센터,5.0,48.0,8100.0

In [7]:
import pandas as pd

file_path='C:/Users/Administrator/Desktop/4장데이터/read.json'
df3= pd.read_json(file_path)

df3

,1.FirstName,2.LastName,3.Age,4.University,5.Courses
0,Gildong,Hong,20,Gachon University,"{'Classes': ['Probability', 'Generalized Linea..."
1,Gildong,Hong,20,Gachon University,"{'Classes': ['Data Structure', 'Programming', ..."

In [11]:
import pandas as pd

#파일경로를 찾고 변수 file_path에 저장
file_path= 'C:/Users/Administrator/Desktop/4장데이터/bicycle.csv'

df4= pd.read_csv(file_path,encoding='CP949')

df4.to_csv('C:/Users/Administrator/Desktop/4장데이터/sample_data.csv')

file_path='C:/Users/Administrator/Desktop/4장데이터/sample_data.csv'
df5=pd.read_csv(file_path)
print(df5)

     Unnamed: 0      자전거번호              대여일시  대여소번호               대여소명  대여거치대  \
0             0  SPB-23220   2019-11-01 8:48    646  장한평역 1번출구 (국민은행앞)    3.0
1             1  SPB-16216   2019-11-04 8:38    646  장한평역 1번출구 (국민은행앞)    2.0
2             2  SPB-21097   2019-11-04 8:46    646  장한평역 1번출구 (국민은행앞)    1.0
3             3  SPB-22292   2019-11-05 8:34    646  장한평역 1번출구 (국민은행앞)    1.0
4             4  SPB-07935  2019-11-05 12:29    512        뚝섬역 1번 출구 옆   11.0
..          ...        ...               ...    ...                ...    ...
415         415  SPB-12116   2019-11-15 4:22    112            극동방송국 앞    5.0
416         416  SPB-17768   2019-11-15 9:31    103         망원역 2번출구 앞   14.0
417         417  SPB-18841  2019-11-15 20:40    113       홍대입구역 2번출구 앞   24.0
418         418  SPB-24467  2019-11-15 21:55    152         마포구민체육센터 앞   18.0
419         419  SPB-17570  2019-11-15 22:16    391              정동길입구    7.0

                 반납일시  반납대여소번호       반납대여소명  반납거치대  이용시간    이용거리
0     2019-11-01 9:01        3         중랑센터    7.0  12.0  1100.0
1     2019-11-04 8:56        3         중랑센터    2.0   7.0  1420.0
2     2019-11-04 8:57        3         중랑센터    7.0  10.0     NaN
3     2019-11-05 8:45        3         중랑센터    NaN  10.0  1380.0
4    2019-11-05 12:39        3         중랑센터    7.0  10.0  1650.0
..                ...      ...          ...    ...   ...     ...
415   2019-11-15 4:33      101  (구)합정동 주민센터    1.0  11.0  2200.0
416   2019-11-15 9:37      101  (구)합정동 주민센터    NaN   5.0     NaN
417  2019-11-15 20:53      101  (구)합정동 주민센터    1.0  12.0  2280.0
418  2019-11-15 22:05      101  (구)합정동 주민센터    1.0  10.0  1180.0
419  2019-11-15 23:04      101  (구)합정동 주민센터    5.0  48.0  8100.0

[420 rows x 12 columns]

In [13]:
import pandas as pd

file_path='C:/Users/Administrator/Desktop/4장데이터/bicycle.xlsx'

df6= pd.read_excel(file_path, encoding='CP949')

df6.to_excel('C:/Users/Administrator/Desktop/4장데이터/sample_data1.xlsx')

file_path='C:/Users/Administrator/Desktop/4장데이터/sample_data1.xlsx'
df7=pd.read_excel(file_path)
print(df7)

TypeError: read_excel() got an unexpected keyword argument 'encoding'

In [14]:
import pandas as pd

#파일경로를 찾고 변수 file_path에 저장
file_path= 'C:/Users/Administrator/Desktop/4장데이터/read.json'

df7= pd.read_json(file_path)
df7

df7.to_json('C:/Users/Administrator/Desktop/4장데이터/sample_data2.json')
df7

,1.FirstName,2.LastName,3.Age,4.University,5.Courses
0,Gildong,Hong,20,Gachon University,"{'Classes': ['Probability', 'Generalized Linea..."
1,Gildong,Hong,20,Gachon University,"{'Classes': ['Data Structure', 'Programming', ..."

In [18]:
import pickle
import pandas as pd

my_list=['a','b','c']

with open("test.pkl","wb") as fw:
    pickle.dump(my_list, fw)
    
with open("test.pkl","rb") as fr:
    data = pickle.load(fr)
print(data)

#temp= pd.DataFrame({'a':[1], 'b':[2]})
#display(temp)

file_path= 'C:/Users/Administrator/Desktop/4장데이터/read.json'

temp= pd.read_json(file_path
                  )
#데이터 저장
temp.to_pickle('filename.pkl')

#데이터 로드
data = pd.read_pickle('filename.pkl')
display(data)

['a', 'b', 'c']

,1.FirstName,2.LastName,3.Age,4.University,5.Courses
0,Gildong,Hong,20,Gachon University,"{'Classes': ['Probability', 'Generalized Linea..."
1,Gildong,Hong,20,Gachon University,"{'Classes': ['Data Structure', 'Programming', ..."