In [43]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt
import seaborn as sns
import numpy as np

file_path='C:/data/WorldCups.csv'

df= pd.read_csv(file_path)

df_year
df

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810

In [41]:
df

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance,Year_c,goal
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549,16,NaN
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000,16,NaN
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700,16,NaN
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246,16,NaN
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607,16,NaN
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810,16,NaN
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172,16,NaN
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135,16,NaN
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975,16,NaN
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753,16,NaN
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791,16,NaN
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723,48,3.041667
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031,48,2.750000
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215,48,2.395833
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538,48,2.937500
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100,64,NaN
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197,64,NaN
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439,64,NaN
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856,64,NaN
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810,64,NaN

In [45]:
df['goal']= df['GoalsScored']/ df['MatchesPlayed']
df

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance,goal
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549,3.888889
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000,4.117647
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700,4.666667
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246,4.000000
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607,5.384615
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810,3.600000
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172,2.781250
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135,2.781250
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975,2.968750
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753,2.552632
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791,2.684211
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723,2.807692
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031,2.538462
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215,2.211538
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538,2.711538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100,2.671875
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197,2.515625
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439,2.296875
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856,2.265625
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810,2.671875